import { z } from "zod";
import { BaseModelSchema } from "../base.schema";
import { TravnexSupportModelSchema } from "./support-llm";
import { AssistantType, LLMType } from "../type-definitions/service-config.definitions";
import { CallTransferConfigSchema } from "./call-transfer-config.schema";

/**
 * @fileoverview Agent configuration schema definitions.
 * @module service-configuration/agent-config
 */

/**
 * Zod schema for Agent Configuration validation.
 *
 * Defines the complete configuration for an AI agent, including model selection,
 * operational modes, instruction sets, and telephony features.
 *
 * @typedef {Object} AgentConfigurationProperties
 * @property {string} id - Unique identifier for the agent configuration
 * @property {string} modelId - Identifier of the LLM model to use for this agent
 * @property {string} name - Human-readable name for the agent configuration
 * @property {LLMType} defaultFunctionState - Default operational mode (text, audio, multimodal) (default: MULTI_MODE)
 * @property {boolean} [usesTravnexSupportModel=true] - Whether this agent uses Travnex's supported model registry
 * @property {Record<string, any>} [requiredModelConfig] - Additional model parameters (e.g., voiceId, languageId)
 * @property {string} instructionConfigurationId - ID of the instruction configuration (role/persona) for this agent
 * @property {AssistantType} assistantType - Type of assistant (web, phone, email, etc.) (default: GENERAL)
 * @property {CallTransferConfig[]} [call_transfer_config=[]] - Array of call transfer configurations
 * @property {Record<string, any>} [metadata] - Additional metadata for the agent configuration
 * @property {TravnexSupportModel | null} [model] - Complete model information from Travnex support registry
 * @property {number} [createdAt] - Timestamp when the configuration was created
 * @property {number} [updatedAt] - Timestamp when the configuration was last updated
 *
 * @example
 * ```typescript
 * const agentConfig: AgentConfiguration = {
 *   id: '123*',
 *   modelId: 'gpt-4',
 *   name: 'Customer Support Agent',
 *   defaultFunctionState: LLMType.MULTI_MODE,
 *   usesTravnexSupportModel: true,
 *   instructionConfigurationId: '456*',
 *   assistantType: AssistantType.PHONE,
 *   call_transfer_config: [
 *     {
 *       transfer_number: '+15551234567',
 *       transfer_type: 'warm',
 *       transfer_conditions: ['billing support', 'escalate']
 *     }
 *   ],
 *   metadata: { department: 'support' },
 *   createdAt: Date.now(),
 *   updatedAt: Date.now()
 * };
 * ```
 */
export const AgentConfigurationSchema = BaseModelSchema.safeExtend({
    modelId: z.string(),
    name: z.string(),
    defaultFunctionState: z.enum(LLMType).default(LLMType.MULTI_MODE),
    usesTravnexSupportModel: z.boolean().optional().default(true),
    requiredModelConfig: z.record(z.string(), z.any()).optional(),
    instructionConfigurationId: z.string(),
    assistantType: z.enum(AssistantType).default(AssistantType.GENERAL),
    call_transfer_config: z.array(CallTransferConfigSchema).optional().default([]),
    metadata: z.record(z.string(), z.any()).optional(),
    model: TravnexSupportModelSchema.nullable().optional(),
});

/**
 * Type definition for Agent Configuration.
 *
 * Represents a complete agent configuration including all metadata,
 * model settings, and operational parameters.
 */
export type AgentConfiguration = z.infer<typeof AgentConfigurationSchema>;

/**
 * Zod schema for creating a new agent configuration.
 *
 * Omits auto-generated fields (id, timestamps, model) that are
 * populated by the system during creation.
 *
 * @remarks
 * This schema enforces required fields for agent creation while excluding
 * fields that are automatically generated by the database or system.
 *
 * @example
 * ```typescript
 * const newAgent: CreateAgentConfiguration = {
 *   modelId: 'gpt-4-turbo',
 *   name: 'Sales Assistant',
 *   defaultFunctionState: LLMType.MULTI_MODE,
 *   usesTravnexSupportModel: true,
 *   instructionConfigurationId: '789*',
 *   assistantType: AssistantType.WEB,
 *   requiredModelConfig: {
 *     voiceId: 'rachel',
 *     languageId: 'en-US'
 *   },
 *   call_transfer_config: [],
 *   metadata: { team: 'sales' }
 * };
 * ```
 */
export const CreateAgentConfigurationSchema = AgentConfigurationSchema.omit({
    id: true,
    createdAt: true,
    updatedAt: true,
    model: true,
});

/**
 * Type definition for creating a new agent configuration.
 *
 * Represents the payload required to create a new agent, excluding
 * system-generated fields.
 */
export type CreateAgentConfiguration = z.infer<typeof CreateAgentConfigurationSchema>;

/**
 * Zod schema for updating an existing agent configuration.
 *
 * All fields from CreateAgentConfigurationSchema are optional (partial),
 * with the id field required to identify the configuration to update.
 *
 * @remarks
 * Supports partial updates - only include the fields you want to modify.
 * The id field is mandatory to specify which agent configuration to update.
 *
 * @example
 * ```typescript
 * const updatePayload: UpdateAgentConfiguration = {
 *   id: '123*',
 *   name: 'Updated Sales Assistant',
 *   metadata: { team: 'enterprise-sales' }
 * };
 * ```
 */
export const UpdateAgentConfigurationSchema = CreateAgentConfigurationSchema.partial().safeExtend({
    id: z.string(),
});

/**
 * Type definition for updating an existing agent configuration.
 *
 * Represents a partial update payload with required id field.
 */
export type UpdateAgentConfiguration = z.infer<typeof UpdateAgentConfigurationSchema>;
