import { z } from "zod";
import { BaseModelSchema } from "../base.schema";
import { BusinessSupportServices } from "../type-definitions/account-definitions";

/**
 * @fileoverview Instruction configuration schema definitions.
 * @module service-configuration/instruction-config
 */

/**
 * Zod schema for Instruction Configuration validation.
 *
 * Defines the complete configuration for agent instructions, including role definition,
 * behavioral guidelines, knowledge sources, and enabled business services.
 *
 * @typedef {Object} InstructionConfigurationProperties
 * @property {string} id - Unique identifier for the instruction configuration
 * @property {string} instructionName - System-readable name (auto-generated based on role)
 * @property {string} role - The role or persona the agent should adopt
 * @property {string} organizationId - ID of the organization that owns this configuration
 * @property {string} introductionMessage - Initial greeting message presented when starting a conversation
 * @property {string} instructions - Detailed instructions guiding agent behavior and responses
 * @property {string} guardrails - Safety and behavioral constraints the agent must follow
 * @property {string[]} [requiredSkills] - Specific skills or capabilities required for this instruction set
 * @property {Record<string, any>} [validationRules] - Custom validation rules for input/output processing
 * @property {string} [serviceId] - ID of the service this instruction configuration is associated with
 * @property {BusinessSupportServices[]} [supportedServices=[]] - Platform services (tools) enabled for this agent
 * @property {string[]} [tools] - Tool identifiers the agent can use with this instruction set
 * @property {boolean} [isTemplate=false] - Whether this is a reusable template for creating other configurations
 * @property {boolean} isPrimary - Whether this is the primary system instruction configuration template
 * @property {Record<string, any>} [metadata] - Additional metadata for the instruction configuration
 * @property {string[]} [knowledgeSourceIds=[]] - IDs of knowledge sources providing context for this instruction set
 * @property {number} [createdAt] - Timestamp when the configuration was created
 * @property {number} [updatedAt] - Timestamp when the configuration was last updated
 *
 * @example
 * ```typescript
 * const instructionConfig: InstructionConfiguration = {
 *   id: 'inst-123',
 *   instructionName: 'customer-support-agent',
 *   role: 'Customer Support Specialist',
 *   organizationId: 'org-456',
 *   introductionMessage: 'Hello! How can I help you today?',
 *   instructions: 'You are a helpful customer support agent...',
 *   guardrails: 'Never share sensitive customer data...',
 *   supportedServices: [BusinessSupportServices.APPOINTMENT_MANAGEMENT],
 *   knowledgeSourceIds: ['kb-789'],
 *   isTemplate: false,
 *   isPrimary: false,
 *   createdAt: Date.now(),
 *   updatedAt: Date.now()
 * };
 * ```
 */
export const InstructionConfigurationSchema = BaseModelSchema.safeExtend({
    instructionName: z.string(),
    role: z.string(),
    organizationId: z.string(),
    introductionMessage: z.string(),
    instructions: z.string(),
    guardrails: z.string(),
    requiredSkills: z.array(z.string()).optional(),
    validationRules: z.record(z.string(), z.any()).optional(),
    serviceId: z.string().optional(),
    supportedServices: z.array(z.enum(BusinessSupportServices)).optional().default([]),
    tools: z.array(z.string()).optional(),
    isTemplate: z.boolean().optional().default(false),
    isPrimary: z.boolean().default(false),
    metadata: z.record(z.string(), z.any()).optional(),
    knowledgeSourceIds: z.array(z.string()).optional().default([]),
});

/**
 * Type definition for Instruction Configuration.
 *
 * Represents a complete instruction configuration including all metadata,
 * behavioral guidelines, and knowledge sources.
 */
export type InstructionConfiguration = z.infer<typeof InstructionConfigurationSchema>;

/**
 * Zod schema for creating a new instruction configuration.
 *
 * Omits auto-generated fields (id, timestamps) that are populated by the system.
 *
 * @remarks
 * This schema enforces required fields for instruction creation while excluding
 * fields that are automatically generated by the system.
 *
 * @example
 * ```typescript
 * const newInstruction: CreateInstructionConfiguration = {
 *   instructionName: 'sales-agent',
 *   role: 'Sales Representative',
 *   organizationId: 'org-456',
 *   introductionMessage: 'Hi! I can help you find the perfect solution.',
 *   instructions: 'You are a knowledgeable sales agent...',
 *   guardrails: 'Always be honest about product capabilities...',
 *   supportedServices: [BusinessSupportServices.PRODUCT_ORDER_MANAGEMENT],
 *   knowledgeSourceIds: ['kb-123'],
 *   isTemplate: false,
 *   isPrimary: false
 * };
 * ```
 */
export const CreateInstructionConfigurationSchema = InstructionConfigurationSchema.omit({
    id: true,
    createdAt: true,
    updatedAt: true,
});

/**
 * Type definition for creating a new instruction configuration.
 *
 * Represents the payload required to create a new instruction configuration,
 * excluding system-generated fields.
 */
export type CreateInstructionConfiguration = z.infer<typeof CreateInstructionConfigurationSchema>;

/**
 * Zod schema for updating an existing instruction configuration.
 *
 * All fields from CreateInstructionConfigurationSchema are optional (partial),
 * with the id field required to identify the configuration to update.
 *
 * @remarks
 * Supports partial updates - only include the fields you want to modify.
 * The id field is mandatory to specify which instruction configuration to update.
 *
 * @example
 * ```typescript
 * const updateInstruction: UpdateInstructionConfiguration = {
 *   id: 'inst-123',
 *   introductionMessage: 'Hello! How may I assist you today?',
 *   guardrails: 'Updated safety guidelines...'
 * };
 * ```
 */
export const UpdateInstructionConfigurationSchema = CreateInstructionConfigurationSchema.partial().safeExtend({
    id: z.string(),
});

/**
 * Type definition for updating an existing instruction configuration.
 *
 * Represents a partial update payload with required id field.
 */
export type UpdateInstructionConfiguration = z.infer<typeof UpdateInstructionConfigurationSchema>;
